const samplers = {
	piano: {
		'C3' : 'samples/piano/piano48.wav',
		'C#3' : 'samples/piano/piano49.wav',
		'D3' : 'samples/piano/piano50.wav',
		'D#3' : 'samples/piano/piano51.wav',
		'E3' : 'samples/piano/piano52.wav',
		'F3' : 'samples/piano/piano53.wav',
		'F#3' : 'samples/piano/piano54.wav',
		'G3' : 'samples/piano/piano55.wav',
		'G#3' : 'samples/piano/piano56.wav',
		'A4' : 'samples/piano/piano57.wav',
		'A#4' : 'samples/piano/piano58.wav',
		'B4' : 'samples/piano/piano59.wav',
		'C4' : 'samples/piano/piano60.wav',
		'C#4' : 'samples/piano/piano61.wav',
		'D4' : 'samples/piano/piano62.wav',
		'D#4' : 'samples/piano/piano63.wav',
		'E4' : 'samples/piano/piano64.wav',
		'F4' : 'samples/piano/piano65.wav',
		'F#4' : 'samples/piano/piano66.wav',
		'G4' : 'samples/piano/piano67.wav',
		'G#4' : 'samples/piano/piano68.wav',
		'A5' : 'samples/piano/piano69.wav',
		'A#5' : 'samples/piano/piano70.wav',
		'B5' : 'samples/piano/piano71.wav',
		'C5' : 'samples/piano/piano72.wav',
		'C#5' : 'samples/piano/piano73.wav',
		'D5' : 'samples/piano/piano74.wav',
		'D#5' : 'samples/piano/piano75.wav',
		'E5' : 'samples/piano/piano76.wav',
		'F5' : 'samples/piano/piano77.wav',
		'F#5' : 'samples/piano/piano78.wav',
		'G5' : 'samples/piano/piano79.wav',
		'G#5' : 'samples/piano/piano80.wav',
		'A6' : 'samples/piano/piano81.wav',
		'A#6' : 'samples/piano/piano82.wav',
		'B6' : 'samples/piano/piano83.wav'
	},
	superSaw: {
		'C3' : 'samples/superSaw/C3.wav',
		'C#3' : 'samples/superSaw/Db3.wav',
		'D3' : 'samples/superSaw/D3.wav',
		'D#3' : 'samples/superSaw/Eb3.wav',
		'E3' : 'samples/superSaw/E3.wav',
		'F3' : 'samples/superSaw/F3.wav',
		'F#3' : 'samples/superSaw/Gb3.wav',
		'G3' : 'samples/superSaw/G3.wav',
		'G#3' : 'samples/superSaw/Ab3.wav',
		'A4' : 'samples/superSaw/A4.wav',
		'A#4' : 'samples/superSaw/Bb4.wav',
		'B4' : 'samples/superSaw/B4.wav',
		'C4' : 'samples/superSaw/C4.wav',
		'C#4' : 'samples/superSaw/Db4.wav',
		'D4' : 'samples/superSaw/D4.wav',
		'D#4' : 'samples/superSaw/Eb4.wav',
		'E4' : 'samples/superSaw/E4.wav',
		'F4' : 'samples/superSaw/F4.wav',
		'F#4' : 'samples/superSaw/Gb4.wav',
		'G4' : 'samples/superSaw/G4.wav',
		'G#4' : 'samples/superSaw/Ab4.wav',
		'A5' : 'samples/superSaw/A5.wav',
		'A#5' : 'samples/superSaw/Bb5.wav',
		'B5' : 'samples/superSaw/B5.wav',
		'C5' : 'samples/superSaw/C5.wav',
		'C#5' : 'samples/superSaw/Db5.wav',
		'D5' : 'samples/superSaw/D5.wav',
		'D#5' : 'samples/superSaw/Eb5.wav',
		'E5' : 'samples/superSaw/E5.wav',
		'F5' : 'samples/superSaw/F5.wav',
		'F#5' : 'samples/superSaw/Gb5.wav',
		'G5' : 'samples/superSaw/G5.wav',
		'G#5' : 'samples/superSaw/Ab5.wav',
		'A6' : 'samples/superSaw/A6.wav',
		'A#6' : 'samples/superSaw/Bb6.wav',
		'B6' : 'samples/superSaw/B6.wav',
		'C6' : 'samples/superSaw/C6.wav'
	}
};

window.getSampler = (sampler, baseUrl) => {
	const smplr = new Tone.Sampler(sampler, () => {
		return Promise.resolve(smplr);
	}, baseUrl || '/sounds/');
};
